
<style> .termos p { text-align: justify; } </style>
                                    <p style="text-align: center"><strong>CONTRATO DE ASSINATURA ENTRE BELLA DA SEMANA E ASSINANTE</strong></p>

                                    <p><strong>IDENTIFICAÇÃO DAS PARTES CONTRATANTES</strong></p>
                                    <p>BELLA ENTRETENIMENTO LTDA., pessoa jurídica de direito privado, com sede em Florianópolis/SC, inscrita no CNPJ sob o n° 04.410.756/0001-60, doravante denominada simplesmente de BELLA.
                                    </p><p>PESSOA FÍSICA OU JURÍDICA identificada no formulário desta página e no cadastramento do banco de dados eletrônico da BELLA, doravante denominada simplesmente ASSINANTE.
                                </p><p>As partes acima identificadas têm, entre si, justo e acertado o presente Contrato de Assinatura, que se regerá pelas cláusulas seguintes e pelas demais disposições legais atinentes.
                            </p><p>Cláusula 1ª. O objeto do presente Contrato consiste em o ASSINANTE ter, à sua disposição, através de meios digitais de transmissão de informações, acesso às áreas de conteúdo do site da BELLA (www.belladasemana.com.br) restrita aos assinantes do site.
                        </p><p>Cláusula 2ª. Poderá o ASSINANTE contratar a assinatura mediante um dos planos a seguir elencados:
                    </p><p>2.1. Plano mensal, que disponibiliza 30 (trinta) dias corridos;
                </p><p>2.2. Plano trimestral, que disponibiliza 90 (noventa) dias corridos;
            </p><p>2.3. Plano semestral, que disponibiliza 180 (cento e oitenta) dias corridos;
        </p><p>2.4. Plano anual, que disponibiliza 365 (trezentos e sessenta e cinco) dias corridos.
    </p><p>Parágrafo primeiro. O ASSINANTE manifestará a opção de seu plano de assinatura na página de cadastramento que, para todos os efeitos jurídicos e legais, considera-se parte integrante deste Contrato.
</p><p>Parágrafo segundo. Todos os planos são autorrenováveis até que seja feito o pedido de cancelamento pelo ASSINANTE. A autorrenovação ocorre no momento do vencimento do prazo estipulado pelo plano de assinatura escolhido pelo ASSINANTE.
</p><p>Parágrafo terceiro. Para solicitar cancelamento de assinatura ou auxílio do suporte o ASSINANTE obriga-se a utilizar o mesmo endereço de e-mail de seu cadastro e, posteriormente, verificar e certificar-se de que a resposta da BELLA não está na caixa de SPAM. Caso o endereço de e-mail fornecido não seja o mesmo do utilizado no cadastro, ou a caixa de SPAM não tenha verificada pelo ASSINANTE, a BELLA não poderá ser responsabilizado pelo não cancelamento da assinatura, por não enviar e-mail de resposta ou pelas perdas e dandos causados por isto.
</p><p>Cláusula 3ª. O ASSINANTE, após formalizado este Instrumento, terá direito ao uso ilimitado de horas, durante o período de tempo de acordo com o plano de assinatura por ele escolhido.
</p><p>Parágrafo primeiro. As partes acordam que é de inteira responsabilidade do ASSINANTE possuir, por sua conta, o equipamento mínimo para acesso (linha telefônica, computador, modem e os softwares necessários à conexão), não se responsabilizando a BELLA pelo acesso do ASSINANTE à internet, incluindo problemas de conexão.
</p><p>Parágrafo segundo. Os sites do Bella da Semana podem conter links para outros sites, parceiros ou patrocinadores. Clicar em um banner ou link direcionará o ASSINANTE a um terceiro site, fora do Bella da Semana. As interações que ocorram entre o ASSINANTE e esta terceira parte ficam entre o ASSINANTE e a terceira parte, não sendo de responsabilidade do Bella da Semana. A BELLA não assume nenhum tipo de responsabilidade pelas ações, produtos, disponibilidade ou conteúdo de tais links externos. O ASSINANTE deve dirigir qualquer comunicação ou reclamação sobre estes sites diretamente ao administrador ou webmaster do referido site.
</p><p>Parágrafo terceiro. A BELLA não se responsabiliza por eventuais danos que venham a ocorrer nos equipamentos do ASSINANTE provocados pelo mau uso de qualquer software, hardware ou conexões.
</p><p>Cláusula 4ª. Para fins de cadastramento, o ASSINANTE criará um nome (login) e uma senha e informará à BELLA todos os dados necessários para seu cadastramento, responsabilizando-se civil e criminalmente por estas informações. Caso os dados informados pelo ASSINANTE no momento do cadastramento estejam errados ou incompletos, impossibilitando sua comprovação e identificação, a BELLA terá o direito de cancelar automaticamente a conta, eximindo-se de qualquer responsabilidade ou ressarcimento ao ASSINANTE.
</p><p>Cláusula 5ª. As partes acordam que, seja qual for o plano de assinatura contratado, o ASSINANTE não terá direito, em hipótese alguma, a conexões simultâneas com o mesmo nome (login) e a mesma senha.
</p><p>Cláusula 6ª. O ASSINANTE será responsável por quaisquer encargos decorrentes da utilização da BELLA em seu nome (login) e/ou com a sua senha, devendo tomar todas as medidas necessárias para impedir a utilização de sua senha por quaisquer terceiros. Caso o assinante envie, empreste, perca, dê ou venda seus dados de acesso ao site, a BELLA poderá, a seu exclusivo critério, cancelar o acesso do assinante, sem restituição das quantias pagas. &nbsp;
</p><p>Cláusula 7ª. O ASSINANTE declara ter conhecimento de que todos os materiais, fotografias, vídeos, softwares, marcas, tecnologias, nomes e programas veiculados pela BELLA (com exceção dos softwares expressamente identificados como de domínio público) são protegidos por direitos autorais, sendo de propriedade da BELLA ou dos provedores independentes. Qualquer violação a esses direitos pelo ASSINANTE ou por terceiro utilizando-se de sua senha será de responsabilidade do ASSINANTE, implicando a adoção das medidas legais aplicáveis e na imediata terminação da assinatura.
</p><p>Parágrafo primeiro. Todos os conteúdos publicados nos sites do Bella da Semana são direcionados para uso particular e não comercial de seus usuários. Todo e qualquer material publicado nos sites (incluindo, mas não se limitando a artigos, fotografias, imagens, ilustrações, vídeos, coletivamente o Conteúdo) são protegidos por direitos autorais, marca registrada e todas as leis de propriedade intelectual aplicáveis e pertencem ou são controlados por Bella Entretenimento Ltda.
</p><p>Parágrafo segundo. O Conteúdo é protegido pelas leis de direitos autorais como um trabalho coletivo e/ou compilação perante as leis brasileiras de propriedade intelectual e convenções internacionais. O ASSINANTE não deve modificar, adaptar, traduzir, exibir, publicar, transmitir, participar na venda, criar trabalhos derivados de, distribuir, demonstrar, decompilar ou de qualquer maneira explorar o Conteúdo contido nos sites do Bella da Semana.
</p><p>Parágrafo terceiro. Copiar ou armazenar qualquer conteúdo para qualquer propósito que não seja o uso pessoal &nbsp;é expressamente proibido sem a prévia e expressa permissão do Bella da Semana. Para se evitar qualquer dúvida, não é permitido ao ASSINANTE ou USUÁRIO usar &nbsp;o conteúdo da BELLA de forma comercial &nbsp;ou incluir qualquer tipo deste Conteúdo (todo ou em parte) em seu site pessoal, blog, ou qualquer outro tipo de website ou mídia sem a expressa autorização da BELLA.
</p><p>Cláusula 8ª. O ASSINANTE indenizará e defenderá a BELLA, seus funcionários, diretores, proprietários, agentes, provedores de informação, afiliados e licenciados (coletivamente as Partes Indenizáveis) de quaisquer responsabilidades ou custos decorrentes de uma quebra destes Termos e Condições de sua parte, incluindo despesas advocatícias. O ASSINANTE deve cooperar com a defesa conforme seja solicitado. O ASSINANTE não deve assinar nenhum tipo de acordo que afete os direitos da BELLA sem o prévio e expresso consentimento da BELLA.
</p><p>Cláusula 9ª. A BELLA não garante que o acesso ou uso de quaisquer dos sites do Bella da Semana disponíveis será contínuo, ininterrupto ou livre de erros, e não dá nenhum tipo de garantia quanto aos resultados obtidos em decorrência de seu uso.
</p><p>Cláusula 10ª. Não é permitido o uso, por parte do ASSINANTE, de qualquer dispositivo, software, ou prática que interfira ou objetive interferir no bom funcionamento do site ou qualquer transação conduzida no site. Não é permitido que o ASSINANTE ocasione carga excessivamente pesada aos servidores e infraestrutura do site. Não é permitido que o ASSINANTE divida sua senha com terceiros ou que utilize sua senha para quaisquer serviços não autorizados.
</p><p>Cláusula 11ª. Este Instrumento é celebrado por prazo indeterminado, entrando em vigor na data de sua celebração eletrônica. Qualquer uma das partes poderá, a qualquer tempo, rescindir o presente Contrato, mediante comunicação por escrito/fax/e-mail à outra parte, sem que isto implique em infração ao presente acordo.
</p><p>Parágrafo primeiro. Para fins de rescisão contratual ou cancelamento de assinatura por iniciativa do ASSINANTE, fica estabelecido que o assinante obriga-se a comunicar seu intuito de rescindir o presente Contrato até 48 (quarenta e oito) horas antes da renovação da respectiva assinatura através da PÁGINA DE CONTATO do site.&nbsp;&nbsp;
</p><p>Parágrafo segundo. A BELLA poderá, a seu próprio critério, terminar ou suspender o acesso de qualquer ASSINANTE, a qualquer tempo, sem prévio aviso, para qualquer um dos sites do Bella da Semana por qualquer ou nenhuma razão, incluindo sem limitação, a quebra do presente Contrato ou a repetida infração de direitos autorais pelo referido usuário.
</p><p>Parágrafo terceiro. Bella, seus agente autorizados, bem como funcionários, podem interromper, suspender ou cancelar o uso de quaisquer sites do Bella da Semana do usuário que quebrar quaisquer de suas obrigações expressas no presente Contrato.
</p><p>Cláusula 12ª. A BELLA poderá alterar, tanto em forma como em conteúdo, suspender ou cancelar, a seu exclusivo critério, a qualquer tempo, quaisquer dos serviços, produtos, utilidade ou aplicação, disponibilizados por si ou por terceiros, independentemente de qualquer aviso ao ASSINANTE, não implicando qualquer infração ao presente Contrato.
</p><p>Cláusula 13ª. As partes acordam que a BELLA poderá, a qualquer tempo, modificar, adicionar ou remover quaisquer cláusulas ou condições deste Contrato. Não havendo concordância do ASSINANTE, este poderá rescindir o presente Contrato, sem qualquer ônus, mediante comunicação por e-mail ou via postal, dentro do prazo de 10 (dez) dias da data da alteração.
</p><p>Cláusula 14ª. O ASSINANTE será responsável pelo uso dos serviços providos pela BELLA, em observância de todas as leis, decretos e regulamentos nacionais, estaduais e municipais aplicáveis, e das Normas de Segurança e Privacidade, e não poderá divulgar as fotos em nenhum site da Internet ou em qualquer outro local.
</p><p>Cláusula 15ª. O ASSINANTE poderá optar pelas modalidades de mensalidades, conforme as opções disponíveis na página de cadastramento que, para todos os efeitos jurídicos e legais, considera-se parte integrante deste Contrato.
</p><p>Parágrafo único. Qualquer atraso no pagamento das mensalidades dará à BELLA o direito de proceder à desativação do acesso do ASSINANTE até o efetivo pagamento.
</p><p>Cláusula 16ª. O ASSINANTE expressamente declara e garante, para todos os fins de direito, ter mais de 18 anos ou o equivalente à maioridade na jurisdição onde reside e possuir autoridade legal para entrar neste acordo; possuir capacidade jurídica para celebrar este Contrato e utilizar os produtos e serviços objeto deste Contrato; ser financeiramente responsável pela utilização dos produtos e serviços objeto deste Contrato; ter condições financeiras de arcar com os pagamentos, custos e despesas decorrentes deste Contrato; reconhecer que o presente Contrato se formaliza, vinculando as partes, com a aceitação eletrônica pelo ASSINANTE, o que fará mediante o clique no espaço "Aceito a contratação do conteúdo do Bella da Semana", conforme abaixo mencionado; que leu e está ciente e de pleno acordo com todos os termos e condições deste Contrato.
</p><p>Cláusula 17ª. Este Contrato constitui o entendimento integral entre o ASSINANTE e a BELLA. O ASSINANTE não poderá ceder a terceiros seus direitos decorrentes deste Contrato sem a prévia anuência por escrito/fax/e-mail da BELLA.
</p><p>Cláusula 18ª. As partes elegem o foro da Comarca de Florianópolis/SC, regido pela legislação brasileira, para dirimir eventuais litígios decorrentes deste Instrumento, excluindo qualquer outro por mais privilegiado que seja.
</p><p>E, por estarem as partes justas e acordadas, o ASSINANTE, clica no espaço "Aceito a contratação do conteúdo do Bella da Semana", reconhecendo que através deste ato fica o presente Contrato formalizado, vinculando as partes, acarretando nos seus jurídicos e legais efeitos.
</p><p>Florianópolis (SC) - BRASIL</p>